version: '3.7'
services:
  zk-server:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - ".:/code"      
      network_mode: bridge
      command: ['/bin/sh','-c', '/code/init.sh']