version: '3.7'
services:
  zk-server:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - "db:/code"      
      network_mode: bridge
      entrypoint: ['/bin/sh', /code/init.sh]

volumes:
  db: